(() => {
  const $ = selector => document.querySelector(selector);
  const labels = { PENDING: 'Chờ xử lý', IN_PROGRESS: 'Đang thực hiện', SUBMITTED: 'Đã nộp', APPROVED: 'Đã duyệt' };
  const statusClass = { PENDING: 'aa-status--pending', IN_PROGRESS: 'aa-status--progress', SUBMITTED: 'aa-status--submitted', APPROVED: 'aa-status--approved' };
  const safe = value => String(value ?? '').trim() || 'Chưa xác định';
  const dueState = (value, status) => { const due = value ? new Date(value) : null, hours = due ? (due.getTime() - Date.now()) / 36e5 : Infinity; if (!due || !['PENDING', 'IN_PROGRESS'].includes(status)) return ''; return hours < 0 ? 'aa-due--late' : hours < 24 ? 'aa-due--soon' : ''; };
  const dueText = (value, status) => { if (!value) return 'Chưa xác định'; const date = new Date(value), formatted = Number.isNaN(date.getTime()) ? 'Chưa xác định' : date.toLocaleString('vi-VN', { hour12: false }); const state = dueState(value, status); return `${formatted}${state === 'aa-due--late' ? ' · Quá hạn' : state === 'aa-due--soon' ? ' · Sắp đến hạn' : ''}`; };
  async function init() {
    const initialBody = $('#taskRows'); if (initialBody) initialBody.innerHTML = '<tr><td colspan="7" class="aa-empty">Đang tải dữ liệu...</td></tr>';
    const user = await AAIR.guard(); if (!user) return;
    window.AAIRNavbar?.mount(user);
    const table = $('table'), head = table?.querySelector('thead tr'), body = $('#taskRows'); table?.classList.add('aa-table'); table?.closest('div.bg-white')?.classList.add('aa-table-shell'); if (head) head.innerHTML = '<th>Tài liệu</th><th>Phiên làm việc</th><th>Người gán nhãn</th><th>Loại</th><th>Trạng thái</th><th>Hạn nộp</th><th>Thao tác</th>';
    const rows = await AAIR.request('/tasks'), session = $('#sessionFilter'), status = $('#statusFilter'), search = $('#taskSearch'); [...new Set(rows.map(row => row.session_name).filter(Boolean))].sort().forEach(value => session.add(new Option(value, value))); [...new Set(rows.map(row => row.status).filter(Boolean))].sort().forEach(value => status.add(new Option(labels[value] || value, value)));
    const pager = document.createElement('div'); pager.className = 'aa-pagination'; table.parentElement.append(pager); let page = 0;
    const render = () => { const query = search.value.trim().toLocaleLowerCase(); const filtered = rows.filter(row => (!query || Object.values(row).filter(value => typeof value !== 'object').join(' ').toLocaleLowerCase().includes(query)) && (!session.value || row.session_name === session.value) && (!status.value || row.status === status.value)); const pages = Math.max(1, Math.ceil(filtered.length / 10)); page = Math.min(page, pages - 1); body.replaceChildren(); const visible = filtered.slice(page * 10, page * 10 + 10); if (!visible.length) { const tr = body.insertRow(); const td = tr.insertCell(); td.colSpan = 7; td.className = 'aa-empty'; td.textContent = 'Không có task phù hợp.'; } visible.forEach(row => { const tr = body.insertRow(); [safe(row.document_title), safe(row.session_name), safe(row.assignee), safe(row.task_type)].forEach(value => { const td = tr.insertCell(); td.textContent = value; }); const statusCell = tr.insertCell(), badge = document.createElement('span'); badge.className = `aa-status ${statusClass[row.status] || 'aa-status--pending'}`; badge.textContent = labels[row.status] || safe(row.status); statusCell.append(badge); const dueCell = tr.insertCell(); dueCell.className = dueState(row.due_at, row.status); dueCell.textContent = dueText(row.due_at, row.status); const actionCell = tr.insertCell(), button = document.createElement('button'); button.className = 'aa-button'; button.type = 'button'; button.textContent = 'Mở'; button.onclick = () => location.assign(`Task.html?id=${row.id}`); actionCell.append(button); }); pager.replaceChildren(); const previous = document.createElement('button'), next = document.createElement('button'); previous.textContent = '‹'; next.textContent = '›'; previous.disabled = page === 0; next.disabled = page >= pages - 1; previous.onclick = () => { page -= 1; render(); }; next.onclick = () => { page += 1; render(); }; const copy = document.createElement('span'); copy.textContent = `${filtered.length ? page * 10 + 1 : 0}–${Math.min((page + 1) * 10, filtered.length)} / ${filtered.length}`; pager.append(previous, copy, next); };
    search.oninput = () => { page = 0; render(); }; session.onchange = status.onchange = () => { page = 0; render(); }; render();
  }
  init().catch(error => { const body = $('#taskRows'); if (body) body.innerHTML = `<tr><td colspan="7" class="aa-empty">${String(error.message || 'Không tải được dữ liệu.')} <button class="aa-button" onclick="location.reload()">Thử lại</button></td></tr>`; });
})();
